import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          <strong>Lunchables</strong>&nbsp;in the vicinity of 50°04&apos;31.5&quot;N 14°25&apos;07.6&quot;E.
        </h1>
      </main>
    </div>
  );
};

export default Home;
